project:touch .nojekyll
  type: website
  output-dir: docs

book:
  title: "R on Databricks Compendium"
  author: "Zac Davies"
  date: "6/20/2024"
  chapters:
    - index.qmd
    - chapters/model_serving.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

