project:
  type: website
  output-dir: docs

execute:
  freeze: auto

book:
  title: "R on Databricks Compendium"
  author: "Zac Davies"
  date: "6/20/2024"
  chapters:
    - index.qmd
    - chapters/model_serving.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

