project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "R on Databricks Compendium"
  author: "Zac Davies"
  reader-mode: true
  date: "6/20/2024"
  site-url: https://zacdav-db.github.io/dbrx-r-compendium/
  repo-url: https://github.com/zacdav-db/dbrx-r-compendium
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: []
  sharing: [twitter, linkedin]
  
  chapters:
    - index.qmd
        
    - part: "Mlflow"
      chapters:
        - chapters/mlflow/log-to-uc.qmd

format:
  html:
    theme: cosmo
    code-line-numbers: true
  pdf:
    documentclass: scrreprt

editor: visual

