project:
  type: book

execute:
  freeze: auto

book:
  title: "R on Databricks Compendium"
  author: "Zac Davies"
  reader-mode: true
  date: "6/20/2024"
  site-url: https://zacdav-db.github.io/dbrx-r-compendium/
  repo-url: https://github.com/zacdav-db/dbrx-r-compendium
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: []
  sharing: [twitter, linkedin]
  
  chapters:
    - index.qmd
        
    - part: "Mlflow"
      chapters:
        - chapters/mlflow/log-to-uc.qmd
        - chapters/mlflow/load-from-uc.qmd
    
    - part: "Package Management"
      chapters: 
        - chapters/pkg-management/fast-installs.qmd
        - chapters/pkg-management/persisting-libs.qmd
        - chapters/pkg-management/renv.qmd
        
    - part: "Data Engineering"
      chapters:
        - chapters/data-eng/odbc-dbplyr.qmd
        - chapters/data-eng/sparkr-migration.qmd

    - part: "Miscellaneous"
      chapters:
        - chapters/misc/htmlwidgets.qmd
        - chapters/misc/odbc-oauth.qmd
    

format:
  html:
    theme: cosmo
    code-line-numbers: true
  pdf:
    documentclass: scrreprt

editor: visual

